# Generated by Django 4.2.1 on 2023-10-19 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctrl_comb', '0002_modelo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelo',
            options={'verbose_name_plural': 'Modelos'},
        ),
        migrations.AlterModelTableComment(
            name='modelo',
            table_comment='Modelos de Vehículos',
        ),
    ]
